/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./static/modules/**/*.js",
    "./static/shared/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f5f4ed",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb59d",
        "tertiary-fixed": "#e3e2df",
        "surface-container-high": "#e9e8e1",
        "surface-tint": "#9d4324",
        "surface-container": "#efeee7",
        "secondary-container": "#e2dfdc",
        "on-primary-fixed": "#390b00",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#464744",
        "surface-variant": "#e3e3dc",
        "on-tertiary-container": "#fefcf8",
        surface: "#fbf9f2",
        "on-primary-fixed-variant": "#7e2c0e",
        "on-tertiary-fixed": "#1b1c1a",
        secondary: "#5f5e5c",
        "outline-variant": "#dcc1b8",
        "secondary-fixed": "#e5e2df",
        "on-primary": "#ffffff",
        "on-secondary-container": "#636260",
        "on-primary-container": "#fffbff",
        "surface-bright": "#fbf9f2",
        "primary-fixed": "#ffdbd0",
        "tertiary-container": "#747572",
        "on-background": "#1b1c18",
        "secondary-fixed-dim": "#c8c6c3",
        "on-secondary-fixed-variant": "#474745",
        "primary-container": "#b95837",
        "on-surface": "#1b1c18",
        primary: "#9a4021",
        "surface-dim": "#dbdad3",
        "on-secondary-fixed": "#1b1c1a",
        "inverse-surface": "#30312c",
        outline: "#89726b",
        "on-surface-variant": "#56423c",
        "inverse-on-surface": "#f2f1ea",
        background: "#fbf9f2",
        "tertiary-fixed-dim": "#c7c7c3",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        tertiary: "#5b5c59",
        "surface-container-highest": "#e3e3dc",
        error: "#ba1a1a",
        "primary-fixed-dim": "#ffb59d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        lg: "40px",
        sm: "12px",
        xl: "64px",
        base: "8px",
        xs: "4px",
        md: "24px",
        margin: "32px",
      },
      fontFamily: {
        "display-xl": ["Georgia", "\"Times New Roman\"", "serif"],
        "label-sm": ["\"Segoe UI\"", "\"PingFang SC\"", "\"Microsoft YaHei\"", "sans-serif"],
        "body-lg": ["\"Segoe UI\"", "\"PingFang SC\"", "\"Microsoft YaHei\"", "sans-serif"],
        "body-md": ["\"Segoe UI\"", "\"PingFang SC\"", "\"Microsoft YaHei\"", "sans-serif"],
        "headline-md": ["Georgia", "\"Times New Roman\"", "serif"],
        "headline-lg": ["Georgia", "\"Times New Roman\"", "serif"],
        sans: ["\"Segoe UI\"", "\"PingFang SC\"", "\"Microsoft YaHei\"", "sans-serif"],
        serif: ["Georgia", "\"Times New Roman\"", "serif"],
      },
      fontSize: {
        "display-xl": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  safelist: [
    {
      pattern: /(bg|text|border|ring)-(slate|sky|emerald|rose|amber|orange|teal|blue|stone)-(50|100|200|300|400|500|600|700|800|900)/,
    },
    {
      pattern: /(translate-x-full|hidden|block|flex|grid)/,
    },
  ],
};
